library(pedtools)
p <- singleton(id = "Angelika", sex = 2)
p <- addChildren(p, mother = "Angelika", nch = 5, sex = c(1,1,1,1,2), ids = c("Eloy", "Toka", "Remijio", "Pedro", "Veronika"))
p <- addChild(p, parents = c("Remijio"), sex = 0)
p <- relabel(p, new = "Gila = Gina", old = 2)
p <- addParents(p, "Gila = Gina")
p <- addChild(p, parents = c(2,4), sex = 2, id = "Yemenke")
p <- addChild(p, parents = c("Yemenke"), sex = 1, id = "Kiwa")
p <- relabel(p, new = "Nanto", old = 5)
p <- addParents(p, "Nanto")
p <- addChild(p, parents = c(5,6), sex = 1, id = "Moi")
p <- addChild(p, parents= c(6), sex = 1, id = "Nenkiray")
p <- addChild(p, parents = c(2,4), sex = 1, id = "Edwin")
p <- addChild(p, parents = c("Edwin"), sex = 0)
p <- relabel(p, new = "Rosa", old = 8)
p <- addChild(p, parents = c("Eloy"), sex = 0)
p <- relabel(p, new = "Beatriz", old = 8)
p <- addChild(p, parents = c("Toka"), sex = 0)
p <- relabel(p, new = "Maria", old = 8)
p <- addChild(p, parents = c("Pedro"), sex = 0)
p <- relabel(p, new = "Laura", old = 8)
plot(p)

