library(tidyverse)
library(jsonlite)

matches <- data.frame() # grabbing all the match-level data (teams, scores, etc.)

for (i in c(21:27,37:41)){ # selecting the season id's corresponding to the free Messi data

  df <- fromJSON(paste("https://raw.githubusercontent.com/statsbomb/open-data/master/data/matches/11/",i,".json",sep=""),flatten=T) %>% data.frame()

  matches <- plyr::rbind.fill(matches,df)

}

events <- data.frame() # grabbing the detailed event-level data

for (i in 1:nrow(matches)){

  df <- fromJSON(paste("https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/",matches$match_id[i],".json",sep=""),flatten=T) %>% data.frame()

  events <- plyr::rbind.fill(events,data.frame(df,match_id=matches$match_id[i]))

}

# combining the match- and event-level data, plus adding goal dummy for each possession, and a unique identifier for each possession

messi <- left_join(events,matches,by="match_id") %>%
  group_by(match_id,possession) %>%
  mutate(goal = sum(shot.outcome.id==97,na.rm=T))

messi$possid <- group_indices(messi)

messi <- messi %>%
  mutate(player.name = recode(player.name,
                              "Adriano Correia Claro"="Adriano",
                              "Aleix Vidal Parreu"="Vidal",
                              "Alexandre Dimitri Song-Billong"="Song",
                              "Alexis Alejandro Sánchez Sánchez"="Alexis",
                              "Aliaksandr Hleb"="Hleb",
                              "Anderson Luís de Souza"="Deco",
                              "Andrés Iniesta Luján"="Iniesta",
                              "Andreu Fontàs Prat"="Fontas",
                              "Arda Turan"="Arda",
                              "Bojan Krkíc Pérez"="Bojan",
                              "Carles Puyol i Saforcada"="Puyol",
                              "Claudio Andrés Bravo Muñoz"="Bravo",
                              "Cristian Tello Herrera"="Tello",
                              "Damià Abella Pérez"="Abella",
                              "Daniel Alves da Silva"="Dani Alves",
                              "David Villa Sánchez"="Villa",
                              "Dmytro Chygrynskiy"="Chygrynskiy",
                              "Douglas Pereira dos Santos"="Douglas",
                              "Eiður Smári Guðjohnsen"="Gudjohnsen",
                              "Eric-Sylvain Bilal Abidal"="Abidal",
                              "Fernando Navarro i Corbacho"="Navarro",
                              "Francesc Fàbregas i Soler"="Fabregas",
                              "Gabriel Alejandro Milito"="Milito",
                              "Gabriel Francisco García de la Torre"="Gabri",
                              "Gerard Deulofeu Lázaro"="Deulofeu",
                              "Gerard Gumbau Garriga"="Gumbau",
                              "Gerard Piqué Bernabéu"="Pique",
                              "Gianluca Zambrotta"="Zambrotta",
                              "Giovani dos Santos Ramírez"="Giovano",
                              "Giovanni van Bronckhorst"="van Bronckhorst",
                              "Gnégnéri Yaya Touré"="Toure",
                              "Henrik Larsson"="Larsson",
                              "Ibrahim Afellay"="Afellay",
                              "Ivan Rakitic"="Rakitic",
                              "Javier Alejandro Mascherano"="Mascherano",
                              "Javier Pedro Saviola Fernández"="Saviola",
                              "Jean Marie Dongou Tsafack"="Dongou",
                              "Jeffren Isaac Suárez Bermúdez"="Jeffren",
                              "Jérémy Mathieu"="Mathieu",
                              "Jonathan dos Santos Ramírez"="Jonathan dos Santos",
                              "Jordi Alba Ramos"="Alba",
                              "Jordi Masip López"="Masip",
                              "José Edmílson Gomes de Moraes"="Edmilson",
                              "José Manuel Pinto Colorado"="Pinto",
                              "José Manuel Rueda Sampedro"="Rueda",
                              "José Martín Cáceres Silva"="Caceres",
                              "Juan Isaac Cuenca López"="Cuenca",
                              "Juliano Haus Belletti"="Belletti",
                              "Lilian Thuram"="Thuram",
                              "Lionel Andrés Messi Cuccittini"="Messi",
                              "Ludovic Giuly"="Giuly",
                              "Luis Alberto Suárez Díaz"="Suarez",
                              "Manuel Agudo Durán"="Nolito",
                              "Marc-André ter Stegen"="ter Stegen",
                              "Marc Bartra Aregall"="Bartra",
                              "Marc Muniesa Martínez"="Muniesa",
                              "Mark van Bommel"="van Bommel",
                              "Martín Montoya Torralbo"="Montoya",
                              "Maximiliano Gastón López"="Maxi Lopez",
                              "Maxwell Scherrer Cabelino Andrade"="Maxwell",
                              "Munir El Haddadi Mohamed"="Munir",
                              "Neymar da Silva Santos Junior"="Neymar",
                              "Oleguer Presas Renom"="Oleguer",
                              "Pedro Eliezer Rodríguez Ledesma"="Pedro",
                              "Rafael Alcântara do Nascimento"="Rafinha",
                              "Rafael Márquez Álvarez"="Marquez",
                              "Rafael Romero Serrano"="Fali",
                              "Ronaldo de Assis Moreira"="Ronaldinho",
                              "Rubén Iván Martínez Andrade"="Ruben",
                              "Samuel Eto'o Fils"="Eto'o",
                              "Sandro Ramírez Castillo"="Sandro",
                              "Santiago Ezquerro Marín"="Ezquerro",
                              "Sergi Roberto Carnicer"="Sergi Roberto",
                              "Sergi Samper Montaña"="Samper",
                              "Sergio Busquets i Burgos"="Busquets",
                              "Sergio Rodríguez García"="Rodri",
                              "Seydou Kéita"="Kéita",
                              "Sylvio Mendes Campos Junior"="Sylvinho",
                              "Thiago Alcântara do Nascimento"="Thiago",
                              "Thiago Motta"="Motta",
                              "Thierry Henry"="Henry",
                              "Thomas Vermaelen"="Vermaelen",
                              "Víctor Sánchez Mata"="Victor Sanchez",
                              "Víctor Valdés Arribas"="Valdes",
                              "Víctor Vázquez Solsona"="Vazquez",
                              "Xavier Hernández Creus"="Xavi",
                              "Zlatan Ibrahimovic"="Zlatan")) %>%
  mutate(pass.recipient.name = recode(pass.recipient.name,
                                      "Adriano Correia Claro"="Adriano",
                                      "Aleix Vidal Parreu"="Vidal",
                                      "Alexandre Dimitri Song-Billong"="Song",
                                      "Alexis Alejandro Sánchez Sánchez"="Alexis",
                                      "Aliaksandr Hleb"="Hleb",
                                      "Anderson Luís de Souza"="Deco",
                                      "Andrés Iniesta Luján"="Iniesta",
                                      "Andreu Fontàs Prat"="Fontas",
                                      "Arda Turan"="Arda",
                                      "Bojan Krkíc Pérez"="Bojan",
                                      "Carles Puyol i Saforcada"="Puyol",
                                      "Claudio Andrés Bravo Muñoz"="Bravo",
                                      "Cristian Tello Herrera"="Tello",
                                      "Damià Abella Pérez"="Abella",
                                      "Daniel Alves da Silva"="Dani Alves",
                                      "David Villa Sánchez"="Villa",
                                      "Dmytro Chygrynskiy"="Chygrynskiy",
                                      "Douglas Pereira dos Santos"="Douglas",
                                      "Eiður Smári Guðjohnsen"="Gudjohnsen",
                                      "Eric-Sylvain Bilal Abidal"="Abidal",
                                      "Fernando Navarro i Corbacho"="Navarro",
                                      "Francesc Fàbregas i Soler"="Fabregas",
                                      "Gabriel Alejandro Milito"="Milito",
                                      "Gabriel Francisco García de la Torre"="Gabri",
                                      "Gerard Deulofeu Lázaro"="Deulofeu",
                                      "Gerard Gumbau Garriga"="Gumbau",
                                      "Gerard Piqué Bernabéu"="Pique",
                                      "Gianluca Zambrotta"="Zambrotta",
                                      "Giovani dos Santos Ramírez"="Giovano",
                                      "Giovanni van Bronckhorst"="van Bronckhorst",
                                      "Gnégnéri Yaya Touré"="Toure",
                                      "Henrik Larsson"="Larsson",
                                      "Ibrahim Afellay"="Afellay",
                                      "Ivan Rakitic"="Rakitic",
                                      "Javier Alejandro Mascherano"="Mascherano",
                                      "Javier Pedro Saviola Fernández"="Saviola",
                                      "Jean Marie Dongou Tsafack"="Dongou",
                                      "Jeffren Isaac Suárez Bermúdez"="Jeffren",
                                      "Jérémy Mathieu"="Mathieu",
                                      "Jonathan dos Santos Ramírez"="Jonathan dos Santos",
                                      "Jordi Alba Ramos"="Alba",
                                      "Jordi Masip López"="Masip",
                                      "José Edmílson Gomes de Moraes"="Edmilson",
                                      "José Manuel Pinto Colorado"="Pinto",
                                      "José Manuel Rueda Sampedro"="Rueda",
                                      "José Martín Cáceres Silva"="Caceres",
                                      "Juan Isaac Cuenca López"="Cuenca",
                                      "Juliano Haus Belletti"="Belletti",
                                      "Lilian Thuram"="Thuram",
                                      "Lionel Andrés Messi Cuccittini"="Messi",
                                      "Ludovic Giuly"="Giuly",
                                      "Luis Alberto Suárez Díaz"="Suarez",
                                      "Manuel Agudo Durán"="Nolito",
                                      "Marc-André ter Stegen"="ter Stegen",
                                      "Marc Bartra Aregall"="Bartra",
                                      "Marc Muniesa Martínez"="Muniesa",
                                      "Mark van Bommel"="van Bommel",
                                      "Martín Montoya Torralbo"="Montoya",
                                      "Maximiliano Gastón López"="Maxi Lopez",
                                      "Maxwell Scherrer Cabelino Andrade"="Maxwell",
                                      "Munir El Haddadi Mohamed"="Munir",
                                      "Neymar da Silva Santos Junior"="Neymar",
                                      "Oleguer Presas Renom"="Oleguer",
                                      "Pedro Eliezer Rodríguez Ledesma"="Pedro",
                                      "Rafael Alcântara do Nascimento"="Rafinha",
                                      "Rafael Márquez Álvarez"="Marquez",
                                      "Rafael Romero Serrano"="Fali",
                                      "Ronaldo de Assis Moreira"="Ronaldinho",
                                      "Rubén Iván Martínez Andrade"="Ruben",
                                      "Samuel Eto'o Fils"="Eto'o",
                                      "Sandro Ramírez Castillo"="Sandro",
                                      "Santiago Ezquerro Marín"="Ezquerro",
                                      "Sergi Roberto Carnicer"="Sergi Roberto",
                                      "Sergi Samper Montaña"="Samper",
                                      "Sergio Busquets i Burgos"="Busquets",
                                      "Sergio Rodríguez García"="Rodri",
                                      "Seydou Kéita"="Kéita",
                                      "Sylvio Mendes Campos Junior"="Sylvinho",
                                      "Thiago Alcântara do Nascimento"="Thiago",
                                      "Thiago Motta"="Motta",
                                      "Thierry Henry"="Henry",
                                      "Thomas Vermaelen"="Vermaelen",
                                      "Víctor Sánchez Mata"="Victor Sanchez",
                                      "Víctor Valdés Arribas"="Valdes",
                                      "Víctor Vázquez Solsona"="Vazquez",
                                      "Xavier Hernández Creus"="Xavi",
                                      "Zlatan Ibrahimovic"="Zlatan"))
